import { App } from "@octokit/app";
import { Octokit } from "@octokit/rest";
import { slug as slugify } from "github-slugger";
import {
  deriveAddonsFromSpells,
  type SpellSubmissionFile,
} from "../spell-submissions/schema";
import type { GuideEnv } from "./env";
import { requireEnv } from "./env";

const textEncoder = new TextEncoder();

const base64Encode = (input: string) => {
  const bytes = textEncoder.encode(input);
  let binary = "";
  bytes.forEach((byte) => {
    binary += String.fromCharCode(byte);
  });
  return btoa(binary);
};

export const createGitHubApp = (env: GuideEnv) =>
  new App({
    appId: requireEnv(env, "GITHUB_APP_ID"),
    privateKey: requireEnv(env, "GITHUB_APP_PRIVATE_KEY"),
    Octokit,
    log: console,
  });

const getInstallationOctokit = async (env: GuideEnv) => {
  const app = createGitHubApp(env);
  const configuredInstallationId = env.GITHUB_APP_INSTALLATION_ID?.trim();

  if (!configuredInstallationId || !/^\d+$/.test(configuredInstallationId)) {
    const installationUrl = await app.getInstallationUrl();
    console.error(
      `Missing GitHub App installation id. Install or configure the GitHub App, then set GITHUB_APP_INSTALLATION_ID to the numeric installation id. Installation URL: ${installationUrl}`,
    );
    throw new Error(
      `GitHub App installation is not configured. Install the app using ${installationUrl}, then set GITHUB_APP_INSTALLATION_ID to the numeric installation id.`,
    );
  }

  return app.getInstallationOctokit(Number(configuredInstallationId));
};

const getShortTimestamp = () =>
  new Date()
    .toISOString()
    .replace(/[-:TZ.]/g, "")
    .slice(0, 14);

const getTarget = (env: GuideEnv) => ({
  owner: env.GITHUB_OWNER || "Ars-Nouveau",
  repo: env.GITHUB_REPO || "Ars-Auxilia",
  baseBranch: env.GITHUB_BASE_BRANCH || "main",
});

const isNotFoundError = (error: unknown) =>
  error &&
  typeof error === "object" &&
  "status" in error &&
  error.status === 404;

const contentExists = async ({
  octokit,
  owner,
  repo,
  path,
  branch,
}: {
  octokit: Awaited<ReturnType<typeof getInstallationOctokit>>;
  owner: string;
  repo: string;
  path: string;
  branch: string;
}) => {
  try {
    await octokit.rest.repos.getContent({
      owner,
      repo,
      path,
      ref: branch,
    });
    return true;
  } catch (error) {
    if (isNotFoundError(error)) return false;
    throw error;
  }
};

const getUniqueSubmissionPath = async ({
  slug,
  timestamp,
  octokit,
  owner,
  repo,
  baseBranch,
}: {
  slug: string;
  timestamp: string;
  octokit: Awaited<ReturnType<typeof getInstallationOctokit>>;
  owner: string;
  repo: string;
  baseBranch: string;
}) => {
  const defaultPath = `apps/ars.guide/src/content/spell-submissions/${slug}.json`;
  const exists = await contentExists({
    octokit,
    owner,
    repo,
    path: defaultPath,
    branch: baseBranch,
  });

  if (!exists) return defaultPath;
  return `apps/ars.guide/src/content/spell-submissions/${slug}-${timestamp}.json`;
};

export const createSpellSubmissionPullRequest = async ({
  env,
  submission,
  username,
}: {
  env: GuideEnv;
  submission: SpellSubmissionFile;
  username: string;
}) => {
  const octokit = await getInstallationOctokit(env);
  const { owner, repo, baseBranch } = getTarget(env);
  const slug = slugify(submission.name) || "spell-submission";
  const timestamp = getShortTimestamp();
  const branchName = `spell-submission/${slug}-${timestamp}`;
  const filePath = await getUniqueSubmissionPath({
    slug,
    timestamp,
    octokit,
    owner,
    repo,
    baseBranch,
  });
  const message = `feat(spell-submission): add ${submission.name} by ${username}`;
  const body = JSON.stringify(submission, null, 2) + "\n";
  const derivedAddons = deriveAddonsFromSpells(submission.spells);

  const { data: baseRef } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${baseBranch}`,
  });

  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseRef.object.sha,
  });

  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: filePath,
    message,
    content: base64Encode(body),
    branch: branchName,
  });

  const { data: pullRequest } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: message,
    head: branchName,
    base: baseBranch,
    body: [
      `Adds a spell submission generated by the Ars Guide submit form.`,
      "",
      `- Spell: ${submission.name}`,
      `- Author: ${submission.author}`,
      submission.userId ? `- Discord user id: ${submission.userId}` : undefined,
      `- Category: ${submission.category}`,
      `- Versions: ${submission.versions.join(", ")}`,
      `- Derived addons: ${derivedAddons.length ? derivedAddons.join(", ") : "none"}`,
      `- File: \`${filePath}\``,
    ]
      .filter(Boolean)
      .join("\n"),
  });

  await octokit.rest.issues.addLabels({
    owner,
    repo,
    issue_number: pullRequest.number,
    labels: ["spell submission"],
  });

  return {
    pullRequestUrl: pullRequest.html_url,
    pullRequestNumber: pullRequest.number,
    branchName,
    filePath,
  };
};
